POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "added logger",
    "author": "derek",
    "URL": "fakeurl3",
    "likes": 12
}

###
GET http://localhost:3003/api/blogs
###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "derekchan",
    "name": "derek chan",
    "password": "password"
}
###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "ro",
    "name": "user",
    "password": "passs"
}
