POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "added logger",
    "author": "derek",
    "URL": "fakeurl3",
    "likes": 12
}

###
GET http://localhost:3003/api/blogs
###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "dchan",
    "name": "derek chan",
    "password": "password"
}
###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "ro",
    "name": "user",
    "password": "passs"
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "dereks blog for testing",
    "author": "derek",
    "URL": "sdfsdf",
    "likes": 12,
    "userId": "64e52fb17568f6e3c6a45da9"
}
###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "dchan",
    "password": "password"
}